package interfaceEditordePlanes;

import editorDePlanes.Accion;
import editorDePlanes.Plan;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.JComboBox;
import org.jdesktop.application.Action;

/**
 *
 * @author mpacheco
 */

public class AmenazaBox extends javax.swing.JFrame {

    /** Creates new form AmenazaBox */

    private Plan plan;
    private Accion accion;
    private Integer nivel;
    private boolean surge_al_mover;
    private InterfaceEditordePlanesView itv;

    public AmenazaBox(Plan plan, Accion accion, boolean surge_al_mover, InterfaceEditordePlanesView itv) {
        initComponents();
        this.plan= plan;
        this.accion= accion;
        this.itv= itv;
        nivel= null;
        this.surge_al_mover= surge_al_mover;
        aceptar.setEnabled(false);
        nivelesPromocion.removeAllItems();
        Vector<Integer> nivsp= plan.promociones(accion);
        for(Enumeration<Integer> e= nivsp.elements(); e.hasMoreElements();)
            nivelesPromocion.addItem(e.nextElement());
        nivelesDegradacion.removeAllItems();
        Vector<Integer> nivsd= plan.degradaciones(accion);
        for(Enumeration<Integer> e= nivsd.elements(); e.hasMoreElements();)
            nivelesDegradacion.addItem(e.nextElement());
        if(nivelesPromocion.getItemCount() > 0 && nivelesDegradacion.getItemCount() > 0){
            promocionar.setEnabled(true);
            promocionar.setSelected(true);
            nivelesPromocion.setEnabled(true);
            degradar.setEnabled(true);
            nivelesDegradacion.setEnabled(true);
        }
        if(nivelesPromocion.getItemCount() > 0 && nivelesDegradacion.getItemCount() <= 0){
            promocionar.setEnabled(true);
            promocionar.setSelected(true);
            nivelesPromocion.setEnabled(true);
            degradar.setEnabled(false);
            nivelesDegradacion.setEnabled(false);
        }
        if(nivelesPromocion.getItemCount() <= 0 && nivelesDegradacion.getItemCount() > 0){
            promocionar.setEnabled(false);
            nivelesPromocion.setEnabled(false);
            degradar.setEnabled(true);
            degradar.setSelected(true);
            nivelesDegradacion.setEnabled(true);
        }
        if(nivelesPromocion.getItemCount() <= 0 && nivelesDegradacion.getItemCount() <= 0){
            promocionar.setEnabled(false);
            nivelesPromocion.setEnabled(false);
            degradar.setEnabled(false);
            nivelesDegradacion.setEnabled(false);
        }
    }
    
    @Action
    public void aceptar(){
       if(nivel != null){
           if(surge_al_mover){
               plan.moverAccionSinAmenaza(accion, nivel);
           }
           else{
               accion.modificarNivel(nivel);
               plan.agregarAccionSinAmenaza(accion);
           }
           itv.reDibujar();
       }
       IntefaceEditordePlanes.getApplication().getMainFrame().setEnabled(true);
       dispose();
    }
    @Action
    public void cancelar(){
        IntefaceEditordePlanes.getApplication().getMainFrame().setEnabled(true);
        dispose();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        aceptar = new javax.swing.JToggleButton();
        cancelar = new javax.swing.JToggleButton();
        nivelesPromocion = new javax.swing.JComboBox();
        nivelesDegradacion = new javax.swing.JComboBox();
        promocionar = new javax.swing.JRadioButton();
        degradar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getResourceMap(AmenazaBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getActionMap(AmenazaBox.class, this);
        aceptar.setAction(actionMap.get("aceptar")); // NOI18N
        aceptar.setFont(resourceMap.getFont("aceptar.font")); // NOI18N
        aceptar.setText(resourceMap.getString("aceptar.text")); // NOI18N
        aceptar.setName("aceptar"); // NOI18N

        cancelar.setAction(actionMap.get("cancelar")); // NOI18N
        cancelar.setFont(resourceMap.getFont("aceptar.font")); // NOI18N
        cancelar.setText(resourceMap.getString("cancelar.text")); // NOI18N
        cancelar.setName("cancelar"); // NOI18N

        nivelesPromocion.setFont(resourceMap.getFont("nivelesPromocion.font")); // NOI18N
        nivelesPromocion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nivelesPromocion.setName("nivelesPromocion"); // NOI18N
        nivelesPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelesPromocionActionPerformed(evt);
            }
        });

        nivelesDegradacion.setFont(resourceMap.getFont("nivelesPromocion.font")); // NOI18N
        nivelesDegradacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nivelesDegradacion.setName("nivelesDegradacion"); // NOI18N
        nivelesDegradacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelesDegradacionActionPerformed(evt);
            }
        });

        buttonGroup1.add(promocionar);
        promocionar.setFont(resourceMap.getFont("degradar.font")); // NOI18N
        promocionar.setText(resourceMap.getString("promocionar.text")); // NOI18N
        promocionar.setName("promocionar"); // NOI18N
        promocionar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                promocionarStateChanged(evt);
            }
        });
        promocionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promocionarActionPerformed(evt);
            }
        });

        buttonGroup1.add(degradar);
        degradar.setFont(resourceMap.getFont("degradar.font")); // NOI18N
        degradar.setText(resourceMap.getString("degradar.text")); // NOI18N
        degradar.setName("degradar"); // NOI18N
        degradar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degradarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(degradar)
                    .addComponent(promocionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nivelesPromocion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelesDegradacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(promocionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(degradar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nivelesPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivelesDegradacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelar)
                            .addComponent(aceptar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void promocionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promocionarActionPerformed
        // TODO add your handling code here:
        if(promocionar.isSelected()){
            nivelesPromocion.setEnabled(true);
            degradar.setSelected(false);
            nivelesDegradacion.setEnabled(false);
            aceptar.setEnabled(false);
        }
    }//GEN-LAST:event_promocionarActionPerformed

    private void degradarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degradarActionPerformed
        // TODO add your handling code here:
        if(degradar.isSelected()){
            nivelesDegradacion.setEnabled(true);
            promocionar.setSelected(false);
            nivelesPromocion.setEnabled(false);
            aceptar.setEnabled(false);
        }
    }//GEN-LAST:event_degradarActionPerformed

    private void promocionarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_promocionarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_promocionarStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_formWindowClosing

    private void nivelesPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelesPromocionActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        if(promocionar.isSelected()){
            nivel= (Integer)cb.getSelectedItem();
            if (nivel!=null)
                aceptar.setEnabled(true);
        }

    }//GEN-LAST:event_nivelesPromocionActionPerformed

    private void nivelesDegradacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelesDegradacionActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        if(degradar.isSelected()){
            nivel= (Integer)cb.getSelectedItem();
            if (nivel!=null)
                aceptar.setEnabled(true);
        }

    }//GEN-LAST:event_nivelesDegradacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton cancelar;
    private javax.swing.JRadioButton degradar;
    private javax.swing.JComboBox nivelesDegradacion;
    private javax.swing.JComboBox nivelesPromocion;
    private javax.swing.JRadioButton promocionar;
    // End of variables declaration//GEN-END:variables

}
