package interfaceEditordePlanes;

import editorDePlanes.Link;
import editorDePlanes.Plan;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.JComboBox;
import org.jdesktop.application.Action;

/**
 *
 * @author mpacheco
 */

public class BorrarLinkBox extends javax.swing.JFrame {

    /** Creates new form BorrarLinkBox */
    private Plan plan;
    private Link link_borrar;
    private InterfaceEditordePlanesView itv;

    public BorrarLinkBox(Plan plan, InterfaceEditordePlanesView itv) {
        initComponents();
        this.plan= plan;
        link_borrar= null;
        this.itv= itv;
        linksBox.removeAllItems();
        borrar.setEnabled(false);
        Vector<Link> links= plan.obtenerLinks();
        for(Enumeration<Link> e= links.elements();e.hasMoreElements();)
            linksBox.addItem(e.nextElement());
        if(linksBox.getItemCount() <= 0){
            borrar.setEnabled(false);
            linksBox.setEnabled(false);
        }
        else{
            borrar.setEnabled(true);
            linksBox.setEnabled(true);
        }
    }
    @Action
    public void borrar() throws CloneNotSupportedException{
        plan.removerLink2(link_borrar);
        itv.reDibujar();
        linksBox.removeAllItems();         
        Vector<Link> links= plan.obtenerLinks();        
        for(Enumeration<Link> e= links.elements();e.hasMoreElements();)
            linksBox.addItem(e.nextElement());
        if(linksBox.getItemCount() <= 0){
            borrar.setEnabled(false);
            linksBox.setEnabled(false);
        }
        itv.setPlanClonado((Plan) plan.clone());
        itv.getOriginador().set(itv.getPlanClonado());
        itv.getPortero().addMemento( itv.getOriginador().salvarEnRecuerdo());

    }
    @Action
    public void aceptar(){
        IntefaceEditordePlanes.getApplication().getMainFrame().setEnabled(true);
        dispose();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linksBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getResourceMap(BorrarLinkBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        linksBox.setFont(resourceMap.getFont("linksBox.font")); // NOI18N
        linksBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        linksBox.setName("linksBox"); // NOI18N
        linksBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linksBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getActionMap(BorrarLinkBox.class, this);
        borrar.setAction(actionMap.get("borrar")); // NOI18N
        borrar.setFont(resourceMap.getFont("borrar.font")); // NOI18N
        borrar.setText(resourceMap.getString("borrar.text")); // NOI18N
        borrar.setName("borrar"); // NOI18N

        aceptar.setAction(actionMap.get("aceptar")); // NOI18N
        aceptar.setFont(resourceMap.getFont("aceptar.font")); // NOI18N
        aceptar.setText(resourceMap.getString("aceptar.text")); // NOI18N
        aceptar.setName("aceptar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(aceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(linksBox, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(borrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(linksBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        aceptar();
    }//GEN-LAST:event_formWindowClosing

    private void linksBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linksBoxActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        link_borrar= (Link)cb.getSelectedItem();
        if(link_borrar !=null && linksBox.getItemCount() > 0)
            borrar.setEnabled(true);
    }//GEN-LAST:event_linksBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton borrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox linksBox;
    // End of variables declaration//GEN-END:variables

}
