package interfaceEditordePlanes;

import editorDePlanes.Plan;
import org.jdesktop.application.Action;

/**
 *
 * @author mpacheco
 */

public class BorrarNivelBox extends javax.swing.JFrame {

    /** Creates new form BorrarNivelBox */
    private Plan plan;
    private Integer nivel;
    private InterfaceEditordePlanesView itv;

    public BorrarNivelBox(Plan plan, InterfaceEditordePlanesView itv) {
        initComponents();
        this.plan= plan;
        this.nivel= new Integer(0);
        this.itv= itv;
        Integer n= plan.cantidadNivelesAcciones();
        if(n == -1){
            numero.setText("-1");
            jSpinner1.setEnabled(false);
            aceptar.setEnabled(false);            
        }
        else{
            numero.setText(n.toString());
            aceptar.setEnabled(true);
        }       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getResourceMap(BorrarNivelBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jSpinner1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        numero.setFont(resourceMap.getFont("jSpinner1.font")); // NOI18N
        numero.setText(resourceMap.getString("numero.text")); // NOI18N
        numero.setName("numero"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getActionMap(BorrarNivelBox.class, this);
        aceptar.setAction(actionMap.get("aceptar")); // NOI18N
        aceptar.setFont(resourceMap.getFont("cancelar.font")); // NOI18N
        aceptar.setText(resourceMap.getString("aceptar.text")); // NOI18N
        aceptar.setName("aceptar"); // NOI18N

        cancelar.setAction(actionMap.get("cancelar")); // NOI18N
        cancelar.setFont(resourceMap.getFont("cancelar.font")); // NOI18N
        cancelar.setText(resourceMap.getString("cancelar.text")); // NOI18N
        cancelar.setName("cancelar"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jSpinner1.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jSpinner1.setFont(resourceMap.getFont("jSpinner1.font")); // NOI18N
        jSpinner1.setName("jSpinner1"); // NOI18N
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numero))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
       nivel= (Integer)jSpinner1.getValue();
       if(nivel >= 0 && nivel <= plan.cantidadNivelesAcciones())
           aceptar.setEnabled(true);
       else{
           jSpinner1.setValue(new Integer(-1));
           aceptar.setEnabled(false);
       }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_formWindowClosing
    @Action
    public void aceptar() throws CloneNotSupportedException{
       nivel= (Integer)jSpinner1.getValue();
       if(nivel >= 0 && nivel <= plan.cantidadNivelesAcciones()){
           plan.borrarNivel(nivel);
           itv.reDibujar();
           itv.setPlanClonado((Plan) plan.clone());
           itv.getOriginador().set(itv.getPlanClonado());
           itv.getPortero().addMemento( itv.getOriginador().salvarEnRecuerdo());
       }
       if(plan.cantidadNivelesAcciones() == -1)
           itv.desabilitarComandos();
    }
    @Action
    public void cancelar(){
        IntefaceEditordePlanes.getApplication().getMainFrame().setEnabled(true);
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel numero;
    // End of variables declaration//GEN-END:variables

}
