package interfaceEditordePlanes;

import com.sun.pdfview.PDFFile;
import com.sun.pdfview.PDFPage;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import javax.swing.ImageIcon;

/**
 *
 * @author mpacheco
 */

public class MenuAyuda extends javax.swing.JFrame {

    private int total=0;
    private Integer pagTotales;
    private Image image2;
    private int index= 0;
    private PDFFile pdfFileGRAL;

    /** Creates new form AyudaLuis */
    public MenuAyuda() throws FileNotFoundException, IOException {
        initComponents();
        getImages ();
        jLabel1.setIcon (new ImageIcon (image2));
        jLabel2.setText(index+1+" - "+pagTotales.toString());
    }

    private void getImages () throws IOException{
      RandomAccessFile raf = new RandomAccessFile ("./docs/informe.pdf", "r");
      FileChannel fc = raf.getChannel ();
      ByteBuffer buf = fc.map (FileChannel.MapMode.READ_ONLY, 0, fc.size ());
      PDFFile pdfFile = new PDFFile (buf);
      pdfFileGRAL=pdfFile;
      total = pdfFile.getNumPages ();
      int numpages= total;
      pagTotales= total;
      PDFPage page = pdfFile.getPage (index);
      Rectangle rect = new Rectangle(0,0, (int)page.getBBox().getWidth(),(int)page.getBBox().getHeight());
      image2=page.getImage(rect.width, rect.height, rect, null, true, true);
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getResourceMap(MenuAyuda.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setToolTipText(resourceMap.getString("jLabel1.toolTipText")); // NOI18N
        jLabel1.setAutoscrolls(true);
        jLabel1.setName("jLabel1"); // NOI18N
        jScrollPane1.setViewportView(jLabel1);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setToolTipText(resourceMap.getString("jButton1.toolTipText")); // NOI18N
        jButton1.setEnabled(false);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setToolTipText(resourceMap.getString("jButton2.toolTipText")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void avanzarPagina(){
      if(index + 1 <= total){
          PDFPage page = pdfFileGRAL.getPage (++index);
          Rectangle rect = new Rectangle(0,0, (int)page.getBBox().getWidth(),(int)page.getBBox().getHeight());
          //image2.flush();
          image2=page.getImage(rect.width, rect.height, rect, null, true, true);
          jButton1.setEnabled(true);
          jLabel1.setIcon(new ImageIcon(image2));
          if (index == total){
             jButton2.setEnabled(false);
             jButton1.setEnabled(true);
          }
          jLabel2.setText(index+" - "+pagTotales.toString());
      }
    }

    public void retrocederPagina(){
      if(index - 1 >= 1){
          PDFPage page = pdfFileGRAL.getPage (--index);
          Rectangle rect = new Rectangle(0,0, (int)page.getBBox().getWidth(),(int)page.getBBox().getHeight());
         //image2.flush();
          image2=page.getImage(rect.width, rect.height, rect, null, true, true);
          jLabel1.setIcon(new ImageIcon(image2));
          if (index == 1){
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
          }
          jLabel2.setText(index+" - "+pagTotales.toString());
      }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        retrocederPagina();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        avanzarPagina();
}//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        volverAInicio();
        IntefaceEditordePlanes.getApplication().getMainFrame().setEnabled(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_LEFT)
            retrocederPagina();
        else
            if (evt.getKeyCode()==KeyEvent.VK_RIGHT)
                avanzarPagina();
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_LEFT)
            retrocederPagina();
        else
            if (evt.getKeyCode()==KeyEvent.VK_RIGHT)
                avanzarPagina();
    }//GEN-LAST:event_jButton1KeyPressed

    private void volverAInicio(){
        index= 0;
        PDFPage page = pdfFileGRAL.getPage (index);
        Rectangle rect = new Rectangle(0,0, (int)page.getBBox().getWidth(),(int)page.getBBox().getHeight());
        image2.flush();
        image2=page.getImage(rect.width, rect.height, rect, null, true, true);
        jLabel1.setIcon(new ImageIcon(image2));
        jButton1.setEnabled(false);
        jButton2.setEnabled(true);
        jLabel2.setText(index+" - "+pagTotales.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
