package interfaceEditordePlanes;

import editorDePlanes.Accion;
import editorDePlanes.Plan;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.JComboBox;
import org.jdesktop.application.Action;

/**
 *
 * @author mpacheco
 */

public class MoverAccionBox extends javax.swing.JFrame {

    /** Creates new form MoverAccionBox */
    private Plan plan;
    private Accion accion_a_mover;
    private Integer nivel_destino;
    private InterfaceEditordePlanesView itv;

    public MoverAccionBox(Plan plan, InterfaceEditordePlanesView itv) {
        initComponents();
        this.plan= plan;
        accion_a_mover= null;
        nivel_destino= null;
        this.itv= itv;
        accionesBox.removeAllItems();
        nivelesBox.removeAllItems();
        mover.setEnabled(false);
        Vector<Accion> acciones= plan.obtenerAcciones();
        if(acciones != null)
            for(Enumeration<Accion> e= acciones.elements();e.hasMoreElements();)
                accionesBox.addItem(e.nextElement());
        else{
            accionesBox.setEnabled(false);
            nivelesBox.setEnabled(false);
        }
    }
    @Action
    public void mover() throws CloneNotSupportedException{
        if(itv.getCheckAmenazaOnline().isSelected()){
            if(!plan.moverAccionVerifAmenaza(accion_a_mover, nivel_destino) && !plan.falloDeLinks()){
                if(plan.promociones(accion_a_mover).size()!=0 || plan.degradaciones(accion_a_mover).size() !=0){
                    itv.mostrarAmenazas(accion_a_mover, true);
                }
                else{
                    plan.getMensaje().amenazaInsalvable(accion_a_mover);
                }
            }
            else{
                itv.reDibujar();}
        }
        else{
            plan.moverAccionSinAmenaza(accion_a_mover, nivel_destino);
            itv.reDibujar();
        }

        //---
        itv.setPlanClonado((Plan) plan.clone());
        itv.getOriginador().set(itv.getPlanClonado());
        itv.getPortero().addMemento( itv.getOriginador().salvarEnRecuerdo());
        //---
        nivelesBox.removeAllItems();
        mover.setEnabled(false);
    }
    @Action
    public void cancelar(){
        IntefaceEditordePlanes.getApplication().getMainFrame().setEnabled(true);
        dispose();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        accionesBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nivelAccion = new javax.swing.JLabel();
        nivelesBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        mover = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getResourceMap(MoverAccionBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("mover.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        accionesBox.setFont(resourceMap.getFont("mover.font")); // NOI18N
        accionesBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        accionesBox.setToolTipText(resourceMap.getString("accionesBox.toolTipText")); // NOI18N
        accionesBox.setName("accionesBox"); // NOI18N
        accionesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionesBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(resourceMap.getFont("mover.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        nivelAccion.setFont(resourceMap.getFont("mover.font")); // NOI18N
        nivelAccion.setText(resourceMap.getString("nivelAccion.text")); // NOI18N
        nivelAccion.setName("nivelAccion"); // NOI18N

        nivelesBox.setFont(resourceMap.getFont("mover.font")); // NOI18N
        nivelesBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nivelesBox.setName("nivelesBox"); // NOI18N
        nivelesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelesBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(resourceMap.getFont("mover.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getActionMap(MoverAccionBox.class, this);
        mover.setAction(actionMap.get("mover")); // NOI18N
        mover.setFont(resourceMap.getFont("mover.font")); // NOI18N
        mover.setText(resourceMap.getString("mover.text")); // NOI18N
        mover.setName("mover"); // NOI18N

        cancelar.setAction(actionMap.get("cancelar")); // NOI18N
        cancelar.setFont(resourceMap.getFont("mover.font")); // NOI18N
        cancelar.setText(resourceMap.getString("cancelar.text")); // NOI18N
        cancelar.setName("cancelar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accionesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivelAccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivelesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(mover)))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(accionesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nivelAccion)
                    .addComponent(jLabel4)
                    .addComponent(nivelesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_formWindowClosing

    private void accionesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionesBoxActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        accion_a_mover= (Accion)cb.getSelectedItem();
        if (accion_a_mover!=null){
            //accion_a_mover= (Accion)cb.getSelectedItem();
            nivelAccion.setText(accion_a_mover.obtenerNivel().toString());
            Integer niveles_totales= plan.cantidadNivelesAcciones();
            nivelesBox.removeAllItems();
            for(Integer i=0; i <= niveles_totales; i++)
                if(i != accion_a_mover.obtenerNivel())
                    nivelesBox.addItem(i);
            if(nivelesBox.getItemCount() > 0)
                nivelesBox.setEnabled(true);
        }
    }//GEN-LAST:event_accionesBoxActionPerformed

    private void nivelesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelesBoxActionPerformed
        // TODO add your handling code here:
       JComboBox cb = (JComboBox)evt.getSource();
        nivel_destino= (Integer)cb.getSelectedItem();
        if (nivel_destino!=null){
            mover.setEnabled(true);
            nivelesBox.setEnabled(true);
        }
    }//GEN-LAST:event_nivelesBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accionesBox;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton mover;
    private javax.swing.JLabel nivelAccion;
    private javax.swing.JComboBox nivelesBox;
    // End of variables declaration//GEN-END:variables

}
