package interfaceEditordePlanes;

import editorDePlanes.Accion;
import editorDePlanes.Link;
import editorDePlanes.Plan;
import editorDePlanes.Predicado;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.JComboBox;
import org.jdesktop.application.Action;

/**
 *
 * @author mpacheco
 */

public class NuevoLinkBox extends javax.swing.JFrame {

    private InterfaceEditordePlanesView itv;
    /** Creates new form NuevoLinkBox */
    public NuevoLinkBox(Plan plan, InterfaceEditordePlanesView itv) {
        initComponents();
        this.plan= plan;
        this.itv= itv;
        a_origen= null;
        a_destino= null;
        pre_comun= null;
        accionesOrigen.removeAllItems();
        accionesOrigen.setEnabled(false);
        accionesDestino.removeAllItems();
        accionesDestino.setEnabled(false);
        predsComun.removeAllItems();
        predsComun.setEnabled(false);
        jButton1.setEnabled(false);
        Integer ind_niveles= plan.cantidadNivelesAcciones();        
        //Al jComboBox1 le meto todas las acciones disponibles incluyendo el estado inicial.
        if(plan.obtenerEstInicial() != null)
            accionesOrigen.addItem(plan.obtenerEstInicial());
        for(int i= 0; i <= ind_niveles; i++){
            Vector<Accion> acciones_nivel= plan.obtenerAccionesDeNivel(new Integer(i));
            if(acciones_nivel != null)
                for(Enumeration<Accion> e= acciones_nivel.elements(); e.hasMoreElements();)
                    accionesOrigen.addItem(e.nextElement());
        }
        if(accionesOrigen.getItemCount() > 0)
            accionesOrigen.setEnabled(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accionesDestino = new javax.swing.JComboBox();
        predsComun = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        accionesOrigen = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getResourceMap(NuevoLinkBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        accionesDestino.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        accionesDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        accionesDestino.setName("accionesDestino"); // NOI18N
        accionesDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionesDestinoActionPerformed(evt);
            }
        });

        predsComun.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        predsComun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        predsComun.setName("predsComun"); // NOI18N
        predsComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predsComunActionPerformed(evt);
            }
        });

        jLabel3.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(interfaceEditordePlanes.IntefaceEditordePlanes.class).getContext().getActionMap(NuevoLinkBox.class, this);
        aceptar.setAction(actionMap.get("aceptar")); // NOI18N
        aceptar.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        aceptar.setText(resourceMap.getString("aceptar.text")); // NOI18N
        aceptar.setName("aceptar"); // NOI18N

        accionesOrigen.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        accionesOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        accionesOrigen.setName("accionesOrigen"); // NOI18N
        accionesOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionesOrigenActionPerformed(evt);
            }
        });

        jButton1.setAction(actionMap.get("insertar")); // NOI18N
        jButton1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(47, 47, 47)
                        .addComponent(predsComun, 0, 276, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(accionesDestino, 0, 276, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(accionesOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(accionesOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(accionesDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(predsComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accionesDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionesDestinoActionPerformed
        // TODO add your handling code here:    
        JComboBox cb = (JComboBox)evt.getSource();
        a_destino= (Accion)cb.getSelectedItem();
        if(a_destino != null && a_origen != null  && a_origen.obtenerNivel() < a_destino.obtenerNivel()){
            predsComun.removeAllItems();
            Vector<Predicado> preds= plan.predicosEnComun(a_origen, a_destino);
            if(preds != null)
                for(Enumeration<Predicado> e= preds.elements(); e.hasMoreElements();)
                    predsComun.addItem(e.nextElement());
            if(predsComun.getItemCount() > 0){
                predsComun.setEnabled(true);
                aceptar.setEnabled(true);
            }
            else{
                predsComun.setEnabled(false);
                aceptar.setEnabled(false);
            }
        }
}//GEN-LAST:event_accionesDestinoActionPerformed

    private void predsComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predsComunActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        pre_comun= (Predicado)cb.getSelectedItem();
        if(pre_comun != null)
            jButton1.setEnabled(true);
}//GEN-LAST:event_predsComunActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        aceptar();
    }//GEN-LAST:event_formWindowClosing

    private void accionesOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionesOrigenActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        a_origen= (Accion)cb.getSelectedItem();
        int nivel_origen= 0;
        int niveles= plan.cantidadNivelesAcciones();
        accionesDestino.removeAllItems();
        if(a_origen!=null){
            for(int i=nivel_origen; i <= niveles; i++){
                Vector<Accion> acciones_nivel= plan.obtenerAccionesDeNivel(new Integer(i));
                if(acciones_nivel != null &&  i > a_origen.obtenerNivel())
                   for(Enumeration<Accion> e= acciones_nivel.elements(); e.hasMoreElements();)
                       accionesDestino.addItem(e.nextElement());
            }
            if(plan.obtenerEstFinal() != null)
                accionesDestino.addItem(plan.obtenerEstFinal());
            if(accionesDestino.getItemCount() > 0){
                accionesDestino.setEnabled(true);
            }
        }
    }//GEN-LAST:event_accionesOrigenActionPerformed

    @Action
    public void aceptar(){
        IntefaceEditordePlanes.getApplication().getMainFrame().setEnabled(true);
        dispose();
    }
    @Action
    public void insertar() throws CloneNotSupportedException{
        Link link_nuevo= new Link(a_origen,a_destino,pre_comun);
        if(plan.agregarLink(link_nuevo)){
            itv.reDibujar();
            //---
            itv.setPlanClonado((Plan) plan.clone());
            itv.getOriginador().set(itv.getPlanClonado());
            itv.getPortero().addMemento( itv.getOriginador().salvarEnRecuerdo());
            //---
        }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accionesDestino;
    private javax.swing.JComboBox accionesOrigen;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox predsComun;
    // End of variables declaration//GEN-END:variables
    private Plan plan;
    Accion a_origen;
    Accion a_destino;
    Predicado pre_comun;
}
